### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ZombieWolfGamer** [astranauta/5etoolsR20#15]
I keep getting this error in Roll20

**Comment by MrLabRat** [comment]
I need more info. What were you doing when that happened?

Feel free to publish screencaps of said error.

**Comment by ZombieWolfGamer** [comment]
I just copied your code into the Roll20 api, and hit save.

**Comment by MrLabRat** [comment]
What code? Just uninstall the script and install it through the normal way.

https://github.com/astranauta/5etoolsR20/raw/master/5etoolsR20.user.js

**Comment by ZombieWolfGamer** [comment]
Ah, okay. I installed it with Tampermonkey, though now I have no idea how
to use it

**Comment by MrLabRat** [comment]
You just need to press the link and install it again. It will reinstall/update the script.

**Comment by InsaneHyena** [comment]
I get a compilation error when I run it. 329 line, symbol 62.

**Comment by MrLabRat** [comment]
@InsaneHyena is that related to this issue?
