### ISSUE TITLE
Roll20 Import Spell List does not Distinguish Spells from different Sources

### ISSUE THREAD

**Issue by dasuberchin** [astranauta/5etoolsR20#22]
The Roll20 Import Spell List has duplicate identical entries for spells from different sources with no indicator of the source.

Example of such spell:
![image](https://user-images.githubusercontent.com/33440383/32706316-b3ad34ce-c7ea-11e7-89c4-21e8cabb817a.png)

Example of how Roll20 Spell Import looks:
![image](https://user-images.githubusercontent.com/33440383/32706325-cb83a8f8-c7ea-11e7-86b5-e979068cdace.png)

Some of these spells are different from source to source, so I would suggest including the source abbreviation with the spell name.  Perhaps manually identify all such spells and label them or just conditionally include source abbreviation if count(spellname) > 1.

**Comment by MrLabRat** [comment]
Latest commit fixes this!
