### ISSUE TITLE
Imported spells don't add correctly

### ISSUE THREAD

**Issue by DamianTheGreat** [astranauta/5etoolsR20#26]
When trying to drag a spell that was imported to a character sheet, it marks them all as rituals. And when I click on them to cast them, it just gives me a an incomplete info box

![](https://i.gyazo.com/6ff79c0e36c67865b9884a7ab4ff72eb.png)

![](https://i.gyazo.com/5c62d81b95314cef270bfdd679e22784.png)

**Comment by MrLabRat** [comment]
This is being solved at the moment.
