### ISSUE TITLE
Puppet and Sense Emotion spells have incorrect info

### ISSUE THREAD

**Issue by Konahrik13** [astranauta/5etoolsR20#3]
Puppet is listed as:
Casting Time: 1 minute
Range: Self

When it should be: 
Casting Time: 1 action
Range: 120 feet

Sense Emotion is listed as: 
Casting Time: Concentration, up to 10 minutes
Duration: Instantaneous

When it should be:
Casting Time: 1 action
Duration: Concentration, up to 10 minutes

**Comment by MrLabRat** [comment]
Fixed!
