### ISSUE TITLE
3D Dice

### ISSUE THREAD

**Issue by Potato-Tyrant** [astranauta/5etoolsR20#30]
Hi there!

I've noticed that using this script the 3D dice you see as DM are wrong, no matter who rolls them...

Every player sees the die rolling and getting a result which is the same as the chat, while the DM sees a completely different roll on screen...

I've already tried removing all the extensions from Chrome and the single scripts from Tampermonkey, and the only one that makes the 3d dice weird is this one.

**Comment by MrLabRat** [comment]
Should be fixed with latest commit
