### ISSUE TITLE
Tokenactions are hardcoded advantage with whisper

### ISSUE THREAD

**Issue by McThyzer** [astranauta/5etoolsR20#47]
I think they should use the chosen options (Public/Whisper/Toggle/Ask & Advantage/Normal/Disadvantage/Ask) for the respective character sheet.

**Comment by astranauta** [comment]
No they are not, check the Settings page before making these accusations
[imgur.com](https://i.imgur.com/1DY6ZaI.png)

**Comment by McThyzer** [comment]
Lines 5567 - 5573

`d20plus.actionMacroPerception = "%{Selected|npc_perception} /w gm &{template:default} {{name=Senses}}  /w gm @{Selected|npc_senses} ";`

> /w gm

`d20plus.actionMacroDrImmunities = "/w gm &{template:default}  [...]`

> /w gm

`d20plus.actionMacroSaves = "/w gm &{template:simple}{{always=1}}`


> /w gm 

&
> always=1


This is what I meant. I would prefer if it would use the @{wtype} and @{rtype} attributes.

**Comment by TheGiddyLimit** [comment]
I'll look into it.
