### ISSUE TITLE
Import Monsters Unresponsive

### ISSUE THREAD

**Issue by a-t-gordon** [astranauta/5etoolsR20#6]
Import Monsters feature seems to be unresponsive, possibly due to the broken update link. Unrelated to "Issue loading from json when parent folder already exists #5" as this tool does not even respond to prompting.

Import Items and Spells still function.

**Comment by Mooogus** [comment]
I am confirm. I can't import monsters as well but spells and items work fine.

**Comment by MrLabRat** [comment]
Fixed with pull https://github.com/astranauta/astranauta.github.io/pull/108
