### ISSUE TITLE
Import Spells button doesn't work

### ISSUE THREAD

**Issue by Yan-Yan2** [astranauta/5etoolsR20#8]
It takes a short while for the Items and Monster list for Import to show up, but the Spell Import list won't pop up at all.

**Comment by MrLabRat** [comment]
Sorry for this! I messed up in one of my commits :/ 

Fixed with my latest pull request!

**Comment by Yan-Yan2** [comment]
Thank you for your time, but forgive me for another question: How do I fix it on my end? I'm very new to this.

**Comment by MrLabRat** [comment]
While @astranauta doesn't pull the commit you can use mine.

Just replace the url in the import spells area with this one

https://raw.githubusercontent.com/MrLabRat/mrlabrat.github.io/master/data/spells.json
